export const bankList = [
  "AMP Bank GO",
  "ANZ",
  "ANZ Plus",
  "Adelaide Bank",
  "Alex Bank",
  "Australian Military Bank",
  "Australian Mutual Bank",
  "Australian Unity Bank",
  "A-Auswide Bank",
  "BOQ Specialist",
  "Bank Australia",
  "Bank of China",
  "Bank of Melbourne",
  "Bank of Queensland",
  "Bank of Sydney",
  "Bank of us",
  "BankSA",
  "Bankwest",
  "Bendigo Bank",
  "Beyond Bank Australia",
  "Border Bank",
  "Broken Hill Bank",
  "CENTRAL MURRAY CREDIT UNION LIMITED",
  "CENTRAL WEST CREDIT UNION LTD",
  "Coastline ",
  "CommBank",
  "Community First Credit Union",
  "Credit Union SA",
  "DDH Graham",
  "Defence Bank Limited",
  "Dnister",
  "Easystreet",
  "FAMILY FIRST",
  "Fire Service Credit Union",
  "FIRST OPTION BANK",
  "G&C MUTUAL BANK",
  "Goldfields Money",
  "Great Southern Bank Business+",
  "HSBC",
  "Deposit account",
  "Heartland Bank",
  "Heritage",
  "HORIZON BANK",
  "IMB Bank",
  "ING",
  "Illawarra Credit Union Ltd",
  "LCU",
  "ME Bank",
  "Macquarie",
  "The Mutual Bank",
  "MyState Bank",
  "NAB",
  "Newcastle Permanent Building Society",
  "NORTHERN INLAND CREDIT UNION LTD.",
  "People's Choice",
  "Police Bank",
  "Qudos Bank",
  "Queensland Country Bank",
  "RACQ Bank",
  "RAMS",
  "RSL Money",
  "Rabobank",
  "Regional Australia Bank",
  "RELIANCE",
  "SCCU",
  "St. George Bank",
  "Asgard",
  "Summerland",
  "Suncorp Bank",
  "TRANSPORT MUTUAL CREDIT UNION LTD",
  "THE CAPRICORNIAN",
  "MACARTHUR CREDIT UNION LTD",
  "Thriday",
  "TCU",
  "Tyro Payments",
  "ubank",
  "UNITY BANK",
  "Up",
  "Virgin Money Australia",
  "Westpac",
  "WOOLWORTHS TEAM BANK",
  "BankWAW",
  "Goulburn Murray Credit Union Co-Operative Ltd",
];
